# Generated by Django 5.1.5 on 2025-01-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=256, verbose_name='genus')),
                ('species', models.CharField(max_length=256, verbose_name='species')),
            ],
        ),
    ]
