# Generated by Django 5.1.5 on 2025-01-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_herbarium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
